name: Hello World Training Workflow

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: echo "Hello World!"
        # List all files in the current directory for comparison before and after actions/checkout@v2.
      - name: check
        run: ls -l
      - name: change the dir 
        uses: actions/checkout@v2
      - name: check the dir 
        run: ls -l
